# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doubler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='doubler.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rdoubler.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32\'\n\x07\x44oubler\x12\x1c\n\x06\x44ouble\x12\x07.Number\x1a\x07.Number\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'doubler_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)



_DOUBLER = _descriptor.ServiceDescriptor(
  name='Doubler',
  full_name='Doubler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=42,
  serialized_end=81,
  methods=[
  _descriptor.MethodDescriptor(
    name='Double',
    full_name='Doubler.Double',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOUBLER)

DESCRIPTOR.services_by_name['Doubler'] = _DOUBLER

# @@protoc_insertion_point(module_scope)
