# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import doubler_pb2 as doubler__pb2


class DoublerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Double = channel.unary_unary(
        '/Doubler/Double',
        request_serializer=doubler__pb2.Number.SerializeToString,
        response_deserializer=doubler__pb2.Number.FromString,
        )


class DoublerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Double(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DoublerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Double': grpc.unary_unary_rpc_method_handler(
          servicer.Double,
          request_deserializer=doubler__pb2.Number.FromString,
          response_serializer=doubler__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Doubler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
